version: '3'
services:
  pyspark:
    container_name: pyspark_container
    image: jupyter/pyspark-notebook:spark-3.4.1
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=notebook
